name: Snyk Security Scans

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Run Snyk for SCA, SAST, and IaC
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Check out the code
        uses: actions/checkout@v3

      # 2. Setup do ambiente (por exemplo, Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3. SCA: Análise de dependências
      - name: Snyk SCA Test
        uses: snyk/actions@v1
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 4. SAST: Análise de código
      - name: Snyk Code Test (SAST)
        uses: snyk/actions@v1
        with:
          args: code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. IaC: Análise de infraestrutura como código (por exemplo, Terraform)
      - name: Snyk IaC Test
        uses: snyk/actions@v1
        with:
          args: iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 