name: Snyk Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    name: Run Snyk for SCA, SAST, and IaC
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Snyk SCA Test
        uses: snyk/actions@v2
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code Test (SAST)
        uses: snyk/actions@v2
        with:
          args: code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk IaC Test
        uses: snyk/actions@v2
        with:
          args: iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}